package com.shadowolf.servlet;

import java.io.IOException;
import javax.servlet.ServletConfig;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/**
 * Servlet implementation class AnnounceServlet
 */
public class AnnounceServlet extends HttpServlet {
	public static final int DEFAULT_MIN_INTERVAL = 600;
	public static final int DEFAULT_INTERVAL = 1800;
	
	private static final long serialVersionUID = 1L;
       
    /**
     * @see HttpServlet#HttpServlet()
     */
    public AnnounceServlet() {
        super();
        // TODO Auto-generated constructor stub
    }

	/**
	 * @see Servlet#init(ServletConfig)
	 */
	public void init() throws ServletException {

	}

	/**
	 * @see HttpServlet#doGet(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		/*
		 * http://wiki.theory.org/BitTorrentSpecification#Tracker_HTTP.2FHTTPS_Protocol
		 * 
		 * request parameters:
		 * info_hash: urlencoded 20-byte SHA1 hash of the value  of the info key from the Metainfo file. Note that the value  will be a bencoded dictionary, given the definition of the info key above.
		 * peer_id: urlencoded 20-byte string used as a unique ID for the client, generated by the client at startup. This is allowed to be any value, and may be binary data. There are currently no guidelines for generating this peer ID. However, one may rightly presume that it must at least be unique for your local machine, thus should probably incorporate things like process ID and perhaps a timestamp recorded at startup. See peer_id below for common client encodings of this field.
		 * port: The port number that the client is listening on. Ports reserved for BitTorrent are typically 6881-6889. Clients may choose to give up if it cannot establish a port within this range.
		 * uploaded: The total amount uploaded (since the client sent the 'started' event to the tracker) in base ten ASCII. While not explicitly stated in the official specification, the concensus is that this should be the total number of bytes uploaded.
		 * downloaded: The total amount downloaded (since the client sent the 'started' event to the tracker) in base ten ASCII. While not explicitly stated in the official specification, the consensus is that this should be the total number of bytes downloaded.
		 * left: The number of bytes this client still has to download, encoded in base ten ASCII.
		 * compact: Setting this to 1 indicates that the client accepts a compact response. The peers list is replaced by a peers string with 6 bytes per peer. The first four bytes are the host (in network byte order), the last two bytes are the port (again in network byte order). It should be noted that some trackers only support compact responses (for saving bandwidth) and either refuse requests without "compact=1" or simply send a compact response unless the request contains "compact=0" (in which case they will refuse the request.)
		 * no_peer_id: Indicates that the tracker can omit peer id field in peers dictionary. This option is ignored if compact is enabled.
		 * event: If specified, must be one of started, completed, stopped, (or empty which is the same as not being specified). If not specified, then this request is one performed at regular intervals.
		      o started: The first request to the tracker must include the event key with this value.
		      o stopped: Must be sent to the tracker if the client is shutting down gracefully.
		      o completed: Must be sent to the tracker when the download completes. However, must not be sent if the download was already 100% complete when the client started. Presumably, this is to allow the tracker to increment the "completed downloads" metric based solely on this event. 
		 * ip: Optional. The true IP address of the client machine, in dotted quad format or rfc3513 defined hexed IPv6 address. Notes: In general this parameter is not necessary as the address of the client can be determined from the IP address from which the HTTP request came. The parameter is only needed in the case where the IP address that the request came in on is not the IP address of the client. This happens if the client is communicating to the tracker through a proxy (or a transparent web proxy/cache.) It also is necessary when both the client and the tracker are on the same local side of a NAT gateway. The reason for this is that otherwise the tracker would give out the internal (RFC1918) address of the client, which is not routable. Therefore the client must explicitly state its (external, routable) IP address to be given out to external peers. Various trackers treat this parameter differently. Some only honor it only if the IP address that the request came in on is in RFC1918 space. Others honor it unconditionally, while others ignore it completely. In case of IPv6 address (e.g.: 2001:db8:1:2::100) it indicates only that client can communicate via IPv6.
		 * numwant: Optional. Number of peers that the client would like to receive from the tracker. This value is permitted to be zero. If omitted, typically defaults to 50 peers.
 		 * key: Optional. An additional identification that is not shared with any users. It is intended to allow a client to prove their identity should their IP address change.
 		 * trackerid: Optional. If a previous announce contained a tracker id, it should be set here. 
		 */
		
		
	}

	protected static String makeResponse(String failure) {
		failure = "d14:failure reason" + failure.length() + ":" + failure + "e\r\n";
		return failure;
	}
	
	protected static String makeResponse(int seeders, int leechers, int[] peers) {
		return makeResponse(seeders, leechers, peers, DEFAULT_INTERVAL, DEFAULT_MIN_INTERVAL);
	}
	
	protected static String makeResponse(int seeders, int leechers, int[] peers, int interval) {
		return makeResponse(seeders, leechers, peers, interval, DEFAULT_MIN_INTERVAL);
	}
	
	protected static String makeResponse(int seeders, int leechers, int[] peers, int interval, int minInterval) {
		/* http://wiki.theory.org/BitTorrentSpecification#Tracker_Response
		 * failure reason: If present, then no other keys may be present. The value is a human-readable error message as to why the request failed (string).
		 * warning message: (new, optional) Similar to failure reason, but the response still gets processed normally. The warning message is shown just like an error.
		 * interval: Interval in seconds that the client should wait between sending regular requests to the tracker
		 * min interval: (optional) Minimum announce interval. If present clients must not reannounce more frequently than this.
		 * tracker id: A string that the client should send back on its next announcements. If absent and a previous announce sent a tracker id, do not discard the old value; keep using it.
		 * complete: number of peers with the entire file, i.e. seeders (integer)
		 * incomplete: number of non-seeder peers, aka "leechers" (integer)
		 * peers: (dictionary model) The value is a list of dictionaries, each with the following keys:
		      o peer id: peer's self-selected ID, as described above for the tracker request (string)
		      o ip: peer's IP address either IPv6 (hexed) or IPv4 (dotted quad) or DNS name (string)
		      o port: peer's port number (integer) 
		  * peers: (binary model) Instead of using the dictionary model described above, the peers value may be a string consisting of multiples of 6 bytes. First 4 bytes are the IP address and last 2 bytes are the port number. All in network (big endian) notation.
	     */
		
		//for failure reason see makeResponse(String failure) {}
		
		String response = "e8:intervali" + interval + "e" + "12:min intervali" + minInterval + 
			"e10:incompletei" + leechers + "d8:completei" + seeders + "5peers" + 
			(6 * peers.length) + ":";
		
		for(int i : peers) {
			response += i;
		}
		
		response += "e\r\n";
		return response;
	}
}
